# ReConfig by duv14 incorporates OneConfig by Polyfrost and contributors.
# See ATTRIBUTIONS.md and LICENSE-RECONFIG.txt. Original copyright notices are retained.
mod.name=ReConfig
mod.id=reconfig
publish.modrinth=AibBIVmj
publish.modrinth.compose-bundle=compose-multiplatform

loom.ignoreDependencyLoomVersionValidation=true
